### ISSUE TITLE
Main Fragment has an incorrect title due to a typo error

### ISSUE THREAD

**Issue by Lucos18** [luigiiorio30/VeichlesList#1]
The home screen presents a typo error in it's title, in the photo attached below presents the title **"Veichles"**, while the correct the correct syntax is **"Vehicles"**.
<img src="https://user-images.githubusercontent.com/58827838/208866683-c6251009-2dc9-485a-80ce-c50ef8934f1e.jpeg" width="250" height="500" />

**Comment by luigiiorio30** [comment]
I verified the existence of the bug and started to fix it.

**Comment by luigiiorio30** [comment]
Fixed the reported string translation mistakes.
![Ptoho-3 (3)](https://user-images.githubusercontent.com/39243394/208875133-54930024-77ac-4a66-8dc0-d3438e6e0151.png)
