### ISSUE TITLE
Wrong input in add screen and wrong information on detail screen

### ISSUE THREAD

**Issue by Lucos18** [luigiiorio30/VeichlesList#2]
The Detail screen and the Add screen presents two errors, the first one on Add screen, where the user can create/add a new car with age of production of **0 or 9999,** where the input is checked only if the length is of the year is lower than **4** character, same error on displacement, and then in in Detail screen it will show up the wrong input done before.
<p float="left">
  <img src="https://user-images.githubusercontent.com/58827838/208872727-792c0527-9521-4ba7-a3ba-204e383bc7a2.jpeg" width="250" height="500" />
  <img src="https://user-images.githubusercontent.com/58827838/208872744-063ff49a-adf9-4ab0-8778-4b37f9aac0d5.jpeg" width="250" height="500" />
</p>

**Comment by luigiiorio30** [comment]
This is a new programmed function that I wish to add.

**Comment by luigiiorio30** [comment]
Added desired control function, for age, you must insert a valid value, same for displacement "min for age is 1800, max 2100" "Min for displacement is 50, max 8000".
