### ISSUE TITLE
Optional field in add car are shown as empty and not invisible on detail car

### ISSUE THREAD

**Issue by Lucos18** [luigiiorio30/VeichlesList#3]
When a user decides to insert a new car but he remains the optional fields empty, in the detail car the optional fields are still shown but with empty values, a better solution is to show the optional fields in the detail car only if the inputs are not empty,
<p float="left">
  <img src="https://user-images.githubusercontent.com/58827838/208875744-b7dc9081-d284-4ae1-87f5-e17bb64620c9.jpeg" width="250" height="500" />
</p>

**Comment by luigiiorio30** [comment]
It was a planned layout improvement that I wanted to correct.

**Comment by luigiiorio30** [comment]
Added "displacement" to required field (see issue #2 for more information about displacement ), only fix i have to do is hide "type" and "type of fuel".

**Comment by luigiiorio30** [comment]
Added the reported function.
![photo_2022-12-22_12-18-36](https://user-images.githubusercontent.com/39243394/209123401-9b96263d-c691-4592-ad4c-f492d82e1102.jpg)
![photo_2022-12-22_12-18-26](https://user-images.githubusercontent.com/39243394/209123403-4d26dc60-8a9b-4a06-b301-983f7f7ebfc6.jpg)
![photo_2022-12-22_12-18-30](https://user-images.githubusercontent.com/39243394/209123404-c2b4f893-87f9-433b-a35f-2cbee75e6f8d.jpg)
![photo_2022-12-22_12-18-33](https://user-images.githubusercontent.com/39243394/209123407-cdf25ac1-495c-493f-bc47-f059aa8f7a94.jpg)
