### ISSUE TITLE
Animation on navigation between detail car and edit car is not resetted correctly

### ISSUE THREAD

**Issue by Lucos18** [luigiiorio30/VeichlesList#4]
When the user navigates between detail car and edit car, the animation or the state of the floating action button is not setted/resetted correctly, and because of this the user when tapping another time the fab, it only does the animation, without showing the other actions of the two fab of delete and edit as shown in the video below.

https://user-images.githubusercontent.com/58827838/208877249-3a7a59fe-b04f-4477-9948-d02d06478246.mp4

**Comment by luigiiorio30** [comment]
Fixed animation on this fragment
